######################################
#                                    #
#   Configuration file for Skyrama   #
#                                    #
######################################

mysql:
    host: localhost
    port: 3306
    name: skyrama
    user: root
    password:

# General plugin settings
general:
    # Language of the plugin (location: './locales/en_US.yml')
    # Avaible: en_US , de_DE
    locale: en_US

    # Name of the world where floating islands spawn
    world: world

    # Adjust the spawn height to the bottom of the world
    spawn:
        X: 0
        Y: 0
        Z: 0

# Island related settings
island:
    # The size of the plot (in chunks) and the distance between islands
    plotsize: 8

    # Enable respawn on island when player die
    respawnIsland: true
