######################################
#                                    #
#   Configuration file for Skyrama   #
#                                    #
######################################

mysql:
    host: localhost
    port: 3306
    name: skyrama
    user: root
    password:

# General plugin settings
general:
    # Language of the plugin (location: './locales/en_US.yml')
    # Avaible: en_US , de_DE
    locale: en_US

    # Name of the world where floating islands spawn
    world: world

# Island related settings
island:
    # The size of the plot and the distance between islands
    plotsize: 32

    # Enable spawn on island when login
    spawnIslandLogin: true

    # Enable respawn on island when player die
    respawnIsland: true
